import matplotlib.pyplot as pl,numpy,pandas
da = pandas.read_csv('five_year_avg.csv')
print(da.head(5))
pl.figure(figsize=(10,10))
pl.title('Various prices over the years',fontdict={'fontweight':'bold','fontsize':18})
pl.plot(da.year,da.avg_sp,'r.-',label='avg_sp')
pl.plot(da.year,da.avg_dividend,'g.-',label='avg_dividend')
pl.plot(da.year,da.avg_real_dividend,'b.-',label='avg_real_dividend')
pl.plot(da.year,da.avg_earnings,'y.-',label='avg_earnings')
pl.plot(da.year,da.avg_real_earning,'m.-',label='avg_real_earnings')
pl.plot(da.year,da.avg_pe10,'k.-',label='avg_pe10')
pl.plot(da.year,da.max_consumer_price_index,'c.-',label='max_consumer_price_index')
pl.plot(da.year,da.avg_long_interest_rate,'r.-',label='avg_long_interest_rate')
pl.plot(da.year,da.avg_real_price,'k.-',label='avg_real_price')
pl.xticks(da.year[::2].tolist()+[2021])
pl.xlabel('Year',fontdict={'fontweight':'bold','fontsize':14})
pl.ylabel('Prices',fontdict={'fontweight':'bold','fontsize':14})
pl.legend()
pl.savefig('five_year_avg_visualization3.png',dpi=300)
pl.show()
